---
title: "p8105_hw5_cx2227"
author: "Chuyue Xiang"
date: "11/7/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
```


## Problem 1

```{r}
library(tidyverse)

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```

```{r}
replace_missing_values = function(vec) {
  if(is.numeric(vec))
  {vec = replace(vec, is.na(vec), round(mean(vec, na.rm = TRUE), digits = 1))}
  else if (is.character(vec)) {
    vec = replace(vec, is.na(vec), "virginica")}
  }
```

```{r}
iris_with_missing %>%
  map_df(~replace_missing_values(.x)) %>%
  knitr::kable()
```

## Problem 2

```{r}
tibble(list.files(path = "./data")) %>% 
  rename(arm_id = `list.files(path = "./data")`) %>% 
  mutate(list1 = "./data/", list2 = str_c(list1, arm_id) ,data = map(list2, read.csv)) %>% 
  unnest() %>% 
  
  pivot_longer(
    cols = starts_with("week"),
    names_to = "week",
    names_prefix = "week_",
    values_to = "data"
    ) %>% 
  subset.data.frame(select = c("arm_id","week","data")) %>% 
  
  ggplot(aes(x = week, y = data, group = arm_id, color = arm_id)) +
  geom_path() +
  labs(
    title = "Observations of two arms of participants over 8 weeks",
    x = "Week", 
    y = "Value"
    ) 
```

 - From the plot, we can see that generally, experiment group had a larger value than the control group. And the experiment group experienced a significant growth during the 8 weeks when control group stayed mostly the same level as they started.
